{% set name = "nccompare" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nccompare-{{ version }}.tar.gz
  sha256: 2f0443c32aba588a8a48667085b4a2419bafb763057992db87e7bd76b6ee280b

build:
  entry_points:
    - ncpare = nccompare.management:start_from_command_line_interface
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - xarray >=2024.6.0,<2025.0.0
    - pandas >=2.2.2,<3.0.0
    - netcdf4 >=1.7.1,<2.0.0
    - rich >=13.7.1,<14.0.0

test:
  imports:
    - nccompare
  commands:
    - pip check
    - ncpare --help
  requires:
    - pip

about:
  home: https://pypi.org/project/nccompare/
  summary: netCDF Comparison Tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anto6715
